version: '3'
services:
  app:
    ## Get the image from hub.docker.com:
    image: talyguryn/home-bot:latest

    # Or build local image:
#    build:
#      context: .
#      dockerfile: 'docker/prod.Dockerfile'

    restart: unless-stopped
    volumes:
      - '.env:/usr/src/app/.env'
    devices:
      - '/dev/snd:/dev/snd'
    privileged: true
