version: '3'
services:
  app:
    build: .
    restart: unless-stopped
    command: bash -c "yarn && yarn start:dev"
    volumes:
      - '.:/usr/src/app'
    devices:
      - '/dev/snd:/dev/snd'
      - /sys/devices/platform/soc/3f200000.gpio:/sys/devices/platform/soc/3f200000.gpio
      - /sys/class/gpio:/sys/class/gpio
    working_dir: /usr/src/app
