version: '3'
services:
  app:
    build: .
    restart: unless-stopped
    command: bash -c "yarn && yarn start:dev"
    volumes:
      - '.:/usr/src/app'
    devices:
      - '/dev/snd:/dev/snd'
    privileged: true
    working_dir: /usr/src/app
